// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NameTags.Data;

#nullable disable

namespace NameTags.Data.Migrations
{
    [DbContext(typeof(NameTagsDbContext))]
    [Migration("20260623133344_AddNameTextDepthOverride")]
    partial class AddNameTextDepthOverride
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("NameTags.Data.Entities.TagName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("TextDepthMmOverride")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TagProjectId", "SortOrder");

                    b.ToTable("TagNames");
                });

            modelBuilder.Entity("NameTags.Data.Entities.TagProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CornerRadiusMm")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurveSegments")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("CustomSvgBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("FontFamilyOrPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("PlateHeightMm")
                        .HasColumnType("REAL");

                    b.Property<float>("PlateThicknessMm")
                        .HasColumnType("REAL");

                    b.Property<float>("PlateWidthMm")
                        .HasColumnType("REAL");

                    b.Property<string>("ShapeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("StarInnerRadiusRatio")
                        .HasColumnType("REAL");

                    b.Property<int>("StarPoints")
                        .HasColumnType("INTEGER");

                    b.Property<float>("TextDepthMm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TagProjects");
                });

            modelBuilder.Entity("NameTags.Data.Entities.TagName", b =>
                {
                    b.HasOne("NameTags.Data.Entities.TagProject", "TagProject")
                        .WithMany("Names")
                        .HasForeignKey("TagProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TagProject");
                });

            modelBuilder.Entity("NameTags.Data.Entities.TagProject", b =>
                {
                    b.Navigation("Names");
                });
#pragma warning restore 612, 618
        }
    }
}
