// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TripPlanner.Infrastructure.Persistence;

#nullable disable

namespace TripPlanner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TripPlannerDbContext))]
    [Migration("20260623212604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TripPlanner.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfirmationNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LinkedTripId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LinkedTripId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.GoalFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FieldType")
                        .HasColumnType("integer");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("GoalFieldDefinitions");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.GoalItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("GoalItems");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.GoalItemFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoalFieldDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GoalItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GoalFieldDefinitionId");

                    b.HasIndex("GoalItemId");

                    b.ToTable("GoalItemFieldValues");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.GoalItemLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoalItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GoalItemId");

                    b.ToTable("GoalItemLinks");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.GoalItemNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoalItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GoalItemId");

                    b.ToTable("GoalItemNotes");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.TaggedItem", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.HasKey("TagId", "EntityType", "EntityId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("TaggedItems");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.TimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("NearestStopId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TimelineEntries");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.TripStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ArriveDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DepartDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsEnd")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStart")
                        .HasColumnType("boolean");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TripStops");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.Whiteboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WishlistLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WishlistLocationId")
                        .IsUnique();

                    b.ToTable("Whiteboards");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.WishlistLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WishlistLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WishlistLocationId");

                    b.ToTable("WishlistLinks");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.WishlistLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WishlistLocations");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.WishlistNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WishlistLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WishlistLocationId");

                    b.ToTable("WishlistNotes");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.WishlistPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccommodationDetails")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateRangeEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateRangeStart")
                        .HasColumnType("date");

                    b.Property<string>("FreeformText")
                        .HasColumnType("text");

                    b.Property<string>("TransportDetails")
                        .HasColumnType("text");

                    b.Property<Guid>("WishlistLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WishlistLocationId")
                        .IsUnique();

                    b.ToTable("WishlistPlans");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.Booking", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.Goal", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.Trip", "LinkedTrip")
                        .WithMany()
                        .HasForeignKey("LinkedTripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedTrip");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.GoalFieldDefinition", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.Goal", "Goal")
                        .WithMany("FieldDefinitions")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.GoalItem", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.Goal", "Goal")
                        .WithMany("Items")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.GoalItemFieldValue", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.GoalFieldDefinition", "GoalFieldDefinition")
                        .WithMany()
                        .HasForeignKey("GoalFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripPlanner.Domain.Entities.GoalItem", "GoalItem")
                        .WithMany("FieldValues")
                        .HasForeignKey("GoalItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoalFieldDefinition");

                    b.Navigation("GoalItem");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.GoalItemLink", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.GoalItem", "GoalItem")
                        .WithMany("Links")
                        .HasForeignKey("GoalItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoalItem");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.GoalItemNote", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.GoalItem", "GoalItem")
                        .WithMany("Notes")
                        .HasForeignKey("GoalItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoalItem");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.TaggedItem", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.Tag", "Tag")
                        .WithMany("TaggedItems")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.TimelineEntry", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.Trip", "Trip")
                        .WithMany("Timeline")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.TripStop", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.Trip", "Trip")
                        .WithMany("Stops")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.Whiteboard", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.WishlistLocation", "WishlistLocation")
                        .WithOne("Whiteboard")
                        .HasForeignKey("TripPlanner.Domain.Entities.Whiteboard", "WishlistLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WishlistLocation");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.WishlistLink", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.WishlistLocation", "WishlistLocation")
                        .WithMany("Links")
                        .HasForeignKey("WishlistLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WishlistLocation");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.WishlistNote", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.WishlistLocation", "WishlistLocation")
                        .WithMany("Notes")
                        .HasForeignKey("WishlistLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WishlistLocation");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.WishlistPlan", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.WishlistLocation", "WishlistLocation")
                        .WithOne("Plan")
                        .HasForeignKey("TripPlanner.Domain.Entities.WishlistPlan", "WishlistLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WishlistLocation");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.Goal", b =>
                {
                    b.Navigation("FieldDefinitions");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.GoalItem", b =>
                {
                    b.Navigation("FieldValues");

                    b.Navigation("Links");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.Tag", b =>
                {
                    b.Navigation("TaggedItems");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Stops");

                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.WishlistLocation", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Notes");

                    b.Navigation("Plan");

                    b.Navigation("Whiteboard");
                });
#pragma warning restore 612, 618
        }
    }
}
